version: "3.8"

services:
  db:
    container_name: mongo_db
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  app:
    container_name: app
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./app:/app
      - ./scripts:/scripts
      - ./assets:/assets
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - DB_URL=mongodb://db/myTestDB
    depends_on:
      - db
    restart: always
